#!/bin/bash -x

exec > >(tee -a /var/tmp/ddc_$$.log) 2>&1

. /usr/local/osmosix/etc/.osmosix.sh
. /usr/local/osmosix/etc/userenv
. /usr/local/osmosix/service/utils/cfgutil.sh
. /usr/local/osmosix/service/utils/agent_util.sh


	sudo yum -y install firewalld
	sudo systemctl unmask firewalld
	sudo systemctl enable firewalld
	sudo systemctl start firewalld

sudo firewall-cmd --permanent --zone=public --add-port=80/tcp
sudo firewall-cmd --permanent --zone=public --add-port=443/tcp
sudo firewall-cmd --reload
