#!/bin/bash

. /utils.sh

env
print_log "$(env)"

cmd=$1
serviceStatus=""


print_log "INSTALL python tools and pip"
yum update -y
yum install -y python-setuptools
easy_install pip
pip install --upgrade pip
pip install --upgrade setuptools

print_log "INSTALL Swift CLI Package"
pip install python-swiftclient

#sudo yum install -y python-pip
#sudo pip install pip --upgrade
#sudo pip install python-swiftclient



print_log "Downloading ss01.py"

# Get the python code for the service
wget -N https://raw.githubusercontent.com/yuqiqueens/cc-ss01/master/ss01.py

# curl https://raw.githubusercontent.com/yuqiqueens/cc-ss01/master/ss01.py --output ss01.py

print_log "RUN - START and run the service"

case $cmd in
        start)
	        print_log "Beginning Start"
	        print_log "Executing ss01.py"
	        python ss01.py start
	        print_log "Start Complete"
	        sleep 6000
	        ;;
        stop)
	        ;;
        suspend)
	        ;;
        resume)
	        ;;
        *)
	        serviceStatus="No Valid Script Argument"
	        exit 127
	        ;;
esac
print_log "Ending Service Script"
